---
- name: Perform custom post bootstrap configs
  block:
  - name: Set configs
    command:
      cmd: "cephadm shell -- ceph config {{ item }}"
    become: true
    when: cephadm_bootstrap_configs | length > 0
    with_items: "{{ cephadm_bootstrap_configs }}"

  delegate_to: "{{ groups['mons'][0] }}"
  run_once: True
